import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from 'next/router'


export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});

const Home: NextPage = () => {
  const { t } = useTranslation("common");

  const router = useRouter();

  const handleLocaleChange = (locale: string) => {
    router.push(router.asPath, router.asPath, { locale });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <select className="select" onChange={(e) => handleLocaleChange(e.target.value)} value={router.locale}>
          {router.locales?.map((locale) => (
            <option key={locale} value={locale}>
              {locale}
            </option>
          ))}
        </select>

        <Button color="primary" variant="contained" sx={{ marginTop: 2 }}>
          {t("welcome")}
        </Button>
        <Button color="secondary" variant="contained" sx={{ marginTop: 2 }}>
          Secondary
        </Button>
        <Button color="warning" variant="contained" sx={{ marginTop: 2 }}>
          Warning
        </Button>
        <Button color="error" variant="contained" sx={{ marginTop: 2 }}>
          Error
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
